// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Application Version: 0.1.3.101
//		Runtime Version: v4.0.30319
//
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
//		Create a new file with a new partial declaration of the contents of this file and edit that instead.
//		You can use the 'SetupUI()`, 'InitializeUI()', and 'DisposeUI()' partial methods to hook into the construction, initialization, and disposal logic.
// </auto-generated>

using Crestron.SimplSharpPro.DeviceSupport;
using EPS.Crestron.Demo.UI.DemoUI.Core;
using System;
using System.Collections.Generic;

namespace EPS.Crestron.Demo.UI.DemoUI.Components
{
	/// <summary>
	/// Auto-generated Main class.
	/// </summary>
	public partial class Main : IDisposable
	{
		/// <summary>
		/// The <see cref="Panel"/> that this object belongs to.
		/// </summary>
		public Panel ParentPanel;

		/// <summary>
		/// Provides access to the Header Page.
		/// </summary>
		public MainComponents.Header Header;

		/// <summary>
		/// Provides access to the Menu Page.
		/// </summary>
		public MainComponents.Menu Menu;

		/// <summary>
		/// Provides access to the SubpageRefLists Page.
		/// </summary>
		public MainComponents.SubpageRefLists SubpageRefLists;

		/// <summary>
		/// Creates a new instance of the class.
		/// </summary>
		/// <param name="parent">The class that is the base parent of this one.</param>
		public Main(Panel parent)
		{
			ParentPanel = parent;
			Header = new MainComponents.Header(ParentPanel);
			Menu = new MainComponents.Menu(ParentPanel);
			SubpageRefLists = new MainComponents.SubpageRefLists(ParentPanel);

			SetupUI();
		}

		/// <summary>
		/// Implement this in accompanying classes in order to setup functionality on the construction of the root class.
		/// No values should be sent to this touchpanel in this method!
		/// </summary>
		partial void SetupUI();

		/// <summary>
		/// Implement this in accompanying classes in order to dispose of objects as needed.
		/// </summary>
		partial void DisposeUI();

		/// <summary>
		/// Implement in accompanying classes in order to send initial values to the touchpanels when the root class Threads are started.
		/// </summary>
		partial void InitializeUI();

		/// <summary>
		/// Attempts to initialize values for the current class.
		/// </summary>
		internal void InitializeValues()
		{
			InitializeUI();
			Header.InitializeValues();
			Menu.InitializeValues();
			SubpageRefLists.InitializeValues();
		}

		/// <summary>
		/// Calls the partial void DisposeUI in order to allow disposing of custom objects.
		/// </summary>
		public void Dispose()
		{
			DisposeUI();
			Header.Dispose();
			Menu.Dispose();
			SubpageRefLists.Dispose();
		}
	}
}
