// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Application Version: 0.1.4.201
//		Runtime Version: v4.0.30319
//
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
//		Create a new file with a new partial declaration of the contents of this file and edit that instead.
//		You can use the 'SetupUI()`, 'InitializeUI()', and 'DisposeUI()' partial methods to hook into the construction, initialization, and disposal logic.
// </auto-generated>

using Crestron.SimplSharpPro.DeviceSupport;
using Evands.EPS.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace EPS.Demo.UI.DemoUI.Components.MainComponents.MenuComponents
{
	/// <summary>
	/// Auto-generated Options class.
	/// </summary>
	public partial class Options : IDisposable, Evands.EPS.Common.IListItemProvider<OptionsItem>, System.ComponentModel.INotifyPropertyChanged
	{
		/// <summary>
		/// The <see cref="Panel"/> that this object belongs to.
		/// </summary>
		public Panel ParentPanel;

		/// <summary>
		/// disableRedraw field.
		/// </summary>
		public bool disableRedraw;

		/// <summary>
		/// itemClicked field.
		/// </summary>
		public ushort itemClicked;

		/// <summary>
		/// isMoving field.
		/// </summary>
		public bool isMoving;

		/// <summary>
		/// itemHeld field.
		/// </summary>
		public ushort itemHeld;

		/// <summary>
		/// scrollToItem field.
		/// </summary>
		public ushort scrollToItem;

		/// <summary>
		/// setNumberofItems field.
		/// </summary>
		public ushort setNumberofItems;

		/// <summary>
		/// Raised when the DisableRedraw value changes.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> DisableRedrawChanged;

		/// <summary>
		/// Raised when the IsMoving value changes.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> IsMovingChanged;

		/// <summary>
		/// Raised when the ItemClicked value changes.
		/// </summary>
		public event EventHandler<UShortValueChangedEventArgs> ItemClickedChanged;

		/// <summary>
		/// Raised when the ItemHeld value changes.
		/// </summary>
		public event EventHandler<UShortValueChangedEventArgs> ItemHeldChanged;

		/// <summary>
		/// Raised when the associated touchpanel event is received.
		/// </summary>
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		/// <summary>
		/// Raised when the ScrollToItem value changes.
		/// </summary>
		public event EventHandler<UShortValueChangedEventArgs> ScrollToItemChanged;

		/// <summary>
		/// Raised when the SetNumberofItems value changes.
		/// </summary>
		public event EventHandler<UShortValueChangedEventArgs> SetNumberofItemsChanged;

		/// <summary>
		/// Gets an enumeration of <see cref="OptionsItem"/> items the list contains.
		/// </summary>
		System.Collections.ObjectModel.ReadOnlyCollection<OptionsItem> Evands.EPS.Common.IListItemProvider<OptionsItem>.Items
		{
			get 
			{
				return new System.Collections.ObjectModel.ReadOnlyCollection<OptionsItem>(this.Items);
			}
		}

		/// <summary>
		/// Gets the array of <see cref="OptionsItem"/> items in the list.
		/// </summary>
		public OptionsItem[] Items { get; private set; }


		/// <summary>
		/// Gets or sets a value indicating whether the <see cref="DisableRedraw"/> join was last set to true or false.
		/// </summary>
		public bool DisableRedraw
		{
			get 
			{
				return disableRedraw;
			}

			set
			{
				var isChanged = disableRedraw != value;
				disableRedraw = value;
				ParentPanel.SendSmartValue(1, (ushort)(1), value);
				var changeEvent = DisableRedrawChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("DisableRedraw"));
					}
				}
			}
		}

		/// <summary>
		/// Gets a value indicating what the <see cref="ItemClicked"/> join was last set to.
		/// </summary>
		public ushort ItemClicked
		{
			get 
			{
				return itemClicked;
			}

			private set
			{
				var isChanged = itemClicked != value;
				itemClicked = value;
				var changeEvent = ItemClickedChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new UShortValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("ItemClicked"));
					}
				}
			}
		}

		/// <summary>
		/// Gets a value indicating whether the <see cref="IsMoving"/> join was last set to true or false.
		/// </summary>
		public bool IsMoving
		{
			get 
			{
				return isMoving;
			}

			private set
			{
				var isChanged = isMoving != value;
				isMoving = value;
				var changeEvent = IsMovingChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("IsMoving"));
					}
				}
			}
		}

		/// <summary>
		/// Gets a value indicating what the <see cref="ItemHeld"/> join was last set to.
		/// </summary>
		public ushort ItemHeld
		{
			get 
			{
				return itemHeld;
			}

			private set
			{
				var isChanged = itemHeld != value;
				itemHeld = value;
				var changeEvent = ItemHeldChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new UShortValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("ItemHeld"));
					}
				}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating what the <see cref="ScrollToItem"/> join was last set to.
		/// </summary>
		public ushort ScrollToItem
		{
			get 
			{
				return scrollToItem;
			}

			set
			{
				var isChanged = scrollToItem != value;
				scrollToItem = value;
				ParentPanel.SendSmartValue(1, (ushort)(3), value);
				var changeEvent = ScrollToItemChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new UShortValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("ScrollToItem"));
					}
				}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating what the <see cref="SetNumberofItems"/> join was last set to.
		/// </summary>
		public ushort SetNumberofItems
		{
			get 
			{
				return setNumberofItems;
			}

			set
			{
				var isChanged = setNumberofItems != value;
				setNumberofItems = value;
				ParentPanel.SendSmartValue(1, (ushort)(4), value);
				var changeEvent = SetNumberofItemsChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new UShortValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("SetNumberofItems"));
					}
				}
			}
		}

		/// <summary>
		/// Creates a new instance of the class.
		/// </summary>
		/// <param name="parent">The class that is the base parent of this one.</param>
		public Options(Panel parent)
		{
			ParentPanel = parent;

			Items = new OptionsItem[20]
			{
				new OptionsItem(ParentPanel, 0, 0, 0, 0),
				new OptionsItem(ParentPanel, 1, 1, 1, 1),
				new OptionsItem(ParentPanel, 2, 2, 2, 2),
				new OptionsItem(ParentPanel, 3, 3, 3, 3),
				new OptionsItem(ParentPanel, 4, 4, 4, 4),
				new OptionsItem(ParentPanel, 5, 5, 5, 5),
				new OptionsItem(ParentPanel, 6, 6, 6, 6),
				new OptionsItem(ParentPanel, 7, 7, 7, 7),
				new OptionsItem(ParentPanel, 8, 8, 8, 8),
				new OptionsItem(ParentPanel, 9, 9, 9, 9),
				new OptionsItem(ParentPanel, 10, 10, 10, 10),
				new OptionsItem(ParentPanel, 11, 11, 11, 11),
				new OptionsItem(ParentPanel, 12, 12, 12, 12),
				new OptionsItem(ParentPanel, 13, 13, 13, 13),
				new OptionsItem(ParentPanel, 14, 14, 14, 14),
				new OptionsItem(ParentPanel, 15, 15, 15, 15),
				new OptionsItem(ParentPanel, 16, 16, 16, 16),
				new OptionsItem(ParentPanel, 17, 17, 17, 17),
				new OptionsItem(ParentPanel, 18, 18, 18, 18),
				new OptionsItem(ParentPanel, 19, 19, 19, 19)
			};

			ParentPanel.Actions.AddUShort(1, 1, (value) => RaiseItemClickedChanged(value));
			ParentPanel.Actions.AddBool(2, 1, (value) => RaiseIsMovingChanged(value));
			ParentPanel.Actions.AddUShort(2, 1, (value) => RaiseItemHeldChanged(value));

			SetupUI();
		}

		/// <summary>
		/// Implement this in accompanying classes in order to setup functionality on the construction of the root class.
		/// No values should be sent to this touchpanel in this method!
		/// </summary>
		partial void SetupUI();

		/// <summary>
		/// Implement this in accompanying classes in order to dispose of objects as needed.
		/// </summary>
		partial void DisposeUI();

		/// <summary>
		/// Implement in accompanying classes in order to send initial values to the touchpanels when the root class Threads are started.
		/// </summary>
		partial void InitializeUI();

		/// <summary>
		/// Attempts to initialize values for the current class.
		/// </summary>
		internal void InitializeValues()
		{
			InitializeUI();
		}

		/// <summary>
		/// Calls the partial void DisposeUI in order to allow disposing of custom objects.
		/// </summary>
		public void Dispose()
		{
			DisposeUI();
			foreach (var i in Items)
			{
				i.Dispose();
			}
		}

		/// <summary>
		/// Sets the value of the <see cref="DisableRedraw"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetDisableRedraw(bool value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(1, (ushort)(1), value, panel);
			var changeEvent = DisableRedrawChanged;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Pulses the DisableRedraw digital signal. Any local signal changed events won't be fired by this method.
		/// </summary>
		/// <param name="duration">The duration in milliseconds to pulse the signal for.</param>
		public void PulseDisableRedraw(int duration)
		{
			ParentPanel.Pulse(1, (uint)(1), duration);
		}

		/// <summary>
		/// Raises the ItemClickedChanged event.
		/// </summary>
		/// <param name="value">The new value of the property.</param>
		private void RaiseItemClickedChanged(ushort value)
		{
			this.ItemClicked = value;
		}

		/// <summary>
		/// Raises the IsMovingChanged event.
		/// </summary>
		/// <param name="value">The new value of the property.</param>
		private void RaiseIsMovingChanged(bool value)
		{
			this.IsMoving = value;
		}

		/// <summary>
		/// Raises the ItemHeldChanged event.
		/// </summary>
		/// <param name="value">The new value of the property.</param>
		private void RaiseItemHeldChanged(ushort value)
		{
			this.ItemHeld = value;
		}

		/// <summary>
		/// Sets the value of the <see cref="ScrollToItem"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetScrollToItem(ushort value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(1, (ushort)(3), value, panel);
			var changeEvent = ScrollToItemChanged;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new UShortValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Sets the value of the <see cref="SetNumberofItems"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetSetNumberofItems(ushort value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(1, (ushort)(4), value, panel);
			var changeEvent = SetNumberofItemsChanged;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new UShortValueChangedEventArgs(value));
			}
		}
	}
}
