// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Application Version: 0.1.3.101
//		Runtime Version: v4.0.30319
//
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
//		Create a new file with a new partial declaration of the contents of this file and edit that instead.
//		You can use the 'SetupUI()`, 'InitializeUI()', and 'DisposeUI()' partial methods to hook into the construction, initialization, and disposal logic.
// </auto-generated>

using Crestron.SimplSharpPro.DeviceSupport;
using Elegant.EPS.Common;
using System;
using System.Collections.Generic;

namespace EPS.Demo.UI.DemoUI.Components.MainComponents.MenuComponents
{
	/// <summary>
	/// Auto-generated OptionsItem class.
	/// </summary>
	public partial class OptionsItem : IDisposable
	{
		/// <summary>
		/// The <see cref="Panel"/> that this object belongs to.
		/// </summary>
		public Panel ParentPanel;

		/// <summary>
		/// The offset amount this item uses for its digital joins.
		/// </summary>
		private ushort digitalOffset = 0;

		/// <summary>
		/// The offset amount this item uses for its analog joins.
		/// </summary>
		private ushort analogOffset = 0;

		/// <summary>
		/// The offset amount this item uses for its serial joins.
		/// </summary>
		private ushort serialOffset = 0;

		/// <summary>
		/// The offset amount this item has.
		/// </summary>
		private ushort itemOffset = 0;

		/// <summary>
		/// Backing field for the <see cref="IsSelected"/> property.
		/// </summary>
		private bool isSelected;

		/// <summary>
		/// Backing field for the <see cref="IsEnabled"/> property.
		/// </summary>
		private bool isEnabled;

		/// <summary>
		/// Backing field for the <see cref="IsVisible"/> property.
		/// </summary>
		private bool isVisible;

		/// <summary>
		/// Backing field for the <see cref="IconAnalog"/> property.
		/// </summary>
		private ushort iconAnalog;

		/// <summary>
		/// Backing field for the <see cref="Text"/> property.
		/// </summary>
		private string text;

		/// <summary>
		/// Backing field for the <see cref="IconSerial"/> property.
		/// </summary>
		private string iconSerial;

		/// <summary>
		/// Raised when the IsSelected value changes.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> IsSelectedChanged;

		/// <summary>
		/// Raised when the button is pressed.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> Pressed;

		/// <summary>
		/// Raised when the button is released.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> Released;

		/// <summary>
		/// Raised when the associated touchpanel event is received.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> StateChanged;

		/// <summary>
		/// Raised when the IsEnabled value changes.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> IsEnabledChanged;

		/// <summary>
		/// Raised when the IsVisible value changes.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> IsVisibleChanged;

		/// <summary>
		/// Raised when the IconAnalog value changes.
		/// </summary>
		public event EventHandler<UShortValueChangedEventArgs> IconAnalogChanged;

		/// <summary>
		/// Raised when the Text value changes.
		/// </summary>
		public event EventHandler<StringValueChangedEventArgs> TextChanged;

		/// <summary>
		/// Raised when the IconSerial value changes.
		/// </summary>
		public event EventHandler<StringValueChangedEventArgs> IconSerialChanged;

		/// <summary>
		/// Gets or sets a value indicating whether the <see cref="IsSelected"/> join was last set to true or false.
		/// </summary>
		public bool IsSelected
		{
			get 
			{
				return isSelected;
			}
			set
			{
				isSelected = value;
				ParentPanel.SendSmartValue(1, (ushort)(11 + this.digitalOffset), value);
				var ce = IsSelectedChanged;
				if (ce != null)
				{
					ce.Invoke(this, new BooleanValueChangedEventArgs(value));
					}
			}
		}

		/// <summary>
		/// Gets a value indicating whether the PressedState is pressed or released.
		/// </summary>
		public bool PressedState { get; set; }


		/// <summary>
		/// Gets or sets a value indicating whether the <see cref="IsEnabled"/> join was last set to true or false.
		/// </summary>
		public bool IsEnabled
		{
			get 
			{
				return isEnabled;
			}
			set
			{
				isEnabled = value;
				ParentPanel.SendSmartValue(1, (ushort)(2011 + this.digitalOffset), value);
				var ce = IsEnabledChanged;
				if (ce != null)
				{
					ce.Invoke(this, new BooleanValueChangedEventArgs(value));
					}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating whether the <see cref="IsVisible"/> join was last set to true or false.
		/// </summary>
		public bool IsVisible
		{
			get 
			{
				return isVisible;
			}
			set
			{
				isVisible = value;
				ParentPanel.SendSmartValue(1, (ushort)(4011 + this.digitalOffset), value);
				var ce = IsVisibleChanged;
				if (ce != null)
				{
					ce.Invoke(this, new BooleanValueChangedEventArgs(value));
					}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating what the <see cref="IconAnalog"/> join was last set to.
		/// </summary>
		public ushort IconAnalog
		{
			get 
			{
				return iconAnalog;
			}
			set
			{
				iconAnalog = value;
				ParentPanel.SendSmartValue(1, (ushort)(11 + this.analogOffset), value);
				var ce = IconAnalogChanged;
				if (ce != null)
				{
					ce.Invoke(this, new UShortValueChangedEventArgs(value));
					}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating what the <see cref="Text"/> join was last set to.
		/// </summary>
		public string Text
		{
			get 
			{
				return text;
			}
			set
			{
				text = value;
				ParentPanel.SendSmartValue(1, (ushort)(11 + this.serialOffset), value);
				var ce = TextChanged;
				if (ce != null)
				{
					ce.Invoke(this, new StringValueChangedEventArgs(value));
					}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating what the <see cref="IconSerial"/> join was last set to.
		/// </summary>
		public string IconSerial
		{
			get 
			{
				return iconSerial;
			}
			set
			{
				iconSerial = value;
				ParentPanel.SendSmartValue(1, (ushort)(2011 + this.serialOffset), value);
				var ce = IconSerialChanged;
				if (ce != null)
				{
					ce.Invoke(this, new StringValueChangedEventArgs(value));
					}
			}
		}

		/// <summary>
		/// Creates a new instance of the class.
		/// </summary>
		/// <param name="parent">The class that is the base parent of this one.</param>
		/// <param name="digitalOffset">The offset amount this item uses for its digital joins.</param>
		/// <param name="analogOffset">The offset amount this item uses for its analog joins.</param>
		/// <param name="serialOffset">The offset amount this item uses for its serial joins.</param>
		/// <param name="itemOffset">The offset amount this item has.</param>
		public OptionsItem(Panel parent, ushort digitalOffset, ushort analogOffset, ushort serialOffset, ushort itemOffset)
		{
			ParentPanel = parent;

			this.digitalOffset = digitalOffset;
			this.analogOffset = analogOffset;
			this.serialOffset = serialOffset;
			this.itemOffset = itemOffset;

			if (this.digitalOffset == 0 && this.analogOffset == 0 && this.serialOffset == 0)
			{
				this.digitalOffset = itemOffset;
				this.analogOffset = itemOffset;
				this.serialOffset = itemOffset;
			}

			ParentPanel.Actions.AddBool((uint)(this.digitalOffset + 11), 1, (value) => RaisePressed(value), true);
			ParentPanel.Actions.AddBool((uint)(this.digitalOffset + 11), 1, (value) => RaiseReleased(value), false);

			SetupUI();
		}

		/// <summary>
		/// Implement this in accompanying classes in order to setup functionality on the construction of the root class.
		/// No values should be sent to this touchpanel in this method!
		/// </summary>
		partial void SetupUI();

		/// <summary>
		/// Implement this in accompanying classes in order to dispose of objects as needed.
		/// </summary>
		partial void DisposeUI();

		/// <summary>
		/// Implement in accompanying classes in order to send initial values to the touchpanels when the root class Threads are started.
		/// </summary>
		partial void InitializeUI();

		/// <summary>
		/// Attempts to initialize values for the current class.
		/// </summary>
		internal void InitializeValues()
		{
			InitializeUI();
		}

		/// <summary>
		/// Calls the partial void DisposeUI in order to allow disposing of custom objects.
		/// </summary>
		public void Dispose()
		{
			DisposeUI();
		}

		/// <summary>
		/// Sets the value of the <see cref="IsSelected"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetIsSelected(bool value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(1, (ushort)(11 + this.digitalOffset), value, panel);
			var ce = IsSelectedChanged;
			if (ce != null)
			{
				ce.Invoke(this, new BooleanValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Pulses the IsSelected digital signal. Any local signal changed events won't be fired by this method.
		/// </summary>
		/// <param name="duration">The duration in milliseconds to pulse the signal for.</param>
		public void PulseIsSelected(int duration)
		{
			ParentPanel.Pulse(1, (uint)(11 + this.digitalOffset), duration);
		}

		/// <summary>
		/// Raises the Pressed event.
		/// </summary>
		/// <param name="value">The pressed event boolean.</param>
		private void RaisePressed(bool value)
		{
			PressedState = true;
			var ce = Pressed;
			if (ce != null)
			{
				ce.Invoke(this, new BooleanValueChangedEventArgs(true));
			}

			var sce = StateChanged;
			if (sce != null)
			{
				sce.Invoke(this, new BooleanValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Raises the Released event.
		/// </summary>
		/// <param name="value">The released event boolean.</param>
		private void RaiseReleased(bool value)
		{
			PressedState = false;
			var ce = Released;
			if (ce != null)
			{
				ce.Invoke(this, new BooleanValueChangedEventArgs(false));
			}

			var sce = StateChanged;
			if (sce != null)
			{
				sce.Invoke(this, new BooleanValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Sets the value of the <see cref="IsEnabled"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetIsEnabled(bool value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(1, (ushort)(2011 + this.digitalOffset), value, panel);
			var ce = IsEnabledChanged;
			if (ce != null)
			{
				ce.Invoke(this, new BooleanValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Pulses the IsEnabled digital signal. Any local signal changed events won't be fired by this method.
		/// </summary>
		/// <param name="duration">The duration in milliseconds to pulse the signal for.</param>
		public void PulseIsEnabled(int duration)
		{
			ParentPanel.Pulse(1, (uint)(2011 + this.digitalOffset), duration);
		}

		/// <summary>
		/// Sets the value of the <see cref="IsVisible"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetIsVisible(bool value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(1, (ushort)(4011 + this.digitalOffset), value, panel);
			var ce = IsVisibleChanged;
			if (ce != null)
			{
				ce.Invoke(this, new BooleanValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Pulses the IsVisible digital signal. Any local signal changed events won't be fired by this method.
		/// </summary>
		/// <param name="duration">The duration in milliseconds to pulse the signal for.</param>
		public void PulseIsVisible(int duration)
		{
			ParentPanel.Pulse(1, (uint)(4011 + this.digitalOffset), duration);
		}

		/// <summary>
		/// Sets the value of the <see cref="IconAnalog"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetIconAnalog(ushort value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(1, (ushort)(11 + this.analogOffset), value, panel);
			var ce = IconAnalogChanged;
			if (ce != null)
			{
				ce.Invoke(this, new UShortValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Sets the value of the <see cref="Text"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetText(string value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(1, (ushort)(11 + this.serialOffset), value, panel);
			var ce = TextChanged;
			if (ce != null)
			{
				ce.Invoke(this, new StringValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Sets the value of the <see cref="IconSerial"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetIconSerial(string value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(1, (ushort)(2011 + this.serialOffset), value, panel);
			var ce = IconSerialChanged;
			if (ce != null)
			{
				ce.Invoke(this, new StringValueChangedEventArgs(value));
			}
		}
	}
}
