// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Application Version: 0.1.4.201
//		Runtime Version: v4.0.30319
//
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
//		Create a new file with a new partial declaration of the contents of this file and edit that instead.
//		You can use the 'SetupUI()`, 'InitializeUI()', and 'DisposeUI()' partial methods to hook into the construction, initialization, and disposal logic.
// </auto-generated>

using Crestron.SimplSharpPro.DeviceSupport;
using Evands.EPS.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace EPS.Demo.UI.DemoUI.Components.MainComponents.TabsComponents
{
	/// <summary>
	/// Auto-generated TabHorizontal class.
	/// </summary>
	public partial class TabHorizontal : IDisposable, Evands.EPS.Common.IListItemProvider<TabHorizontalItem>, System.ComponentModel.INotifyPropertyChanged
	{
		/// <summary>
		/// The <see cref="Panel"/> that this object belongs to.
		/// </summary>
		public Panel ParentPanel;

		/// <summary>
		/// string1 field.
		/// </summary>
		public string string1;

		/// <summary>
		/// Raised when the associated touchpanel event is received.
		/// </summary>
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		/// <summary>
		/// Raised when the String1 value changes.
		/// </summary>
		public event EventHandler<StringValueChangedEventArgs> String1Changed;

		/// <summary>
		/// Gets an enumeration of <see cref="TabHorizontalItem"/> items the list contains.
		/// </summary>
		System.Collections.ObjectModel.ReadOnlyCollection<TabHorizontalItem> Evands.EPS.Common.IListItemProvider<TabHorizontalItem>.Items
		{
			get 
			{
				return new System.Collections.ObjectModel.ReadOnlyCollection<TabHorizontalItem>(this.Items);
			}
		}

		/// <summary>
		/// Gets or sets the array of <see cref="TabHorizontalItem"/> items in the list.
		/// </summary>
		public TabHorizontalItem[] Items { get; private set; }


		/// <summary>
		/// Gets or sets a value indicating what the <see cref="String1"/> join was last set to.
		/// </summary>
		public string String1
		{
			get 
			{
				return string1;
			}

			set
			{
				var isChanged = string1 != value;
				string1 = value;
				ParentPanel.SendSmartValue(5, (ushort)(425), value);
				var changeEvent = String1Changed;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new StringValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("String1"));
					}
				}
			}
		}

		/// <summary>
		/// Creates a new instance of the class.
		/// </summary>
		/// <param name="parent">The class that is the base parent of this one.</param>
		public TabHorizontal(Panel parent)
		{
			ParentPanel = parent;

			Items = new TabHorizontalItem[3]
			{
				new TabHorizontalItem(ParentPanel, 0, 0, 0, 0),
				new TabHorizontalItem(ParentPanel, 0, 0, 0, 1),
				new TabHorizontalItem(ParentPanel, 0, 0, 0, 2)
			};

			SetupUI();
		}

		/// <summary>
		/// Implement this in accompanying classes in order to setup functionality on the construction of the root class.
		/// No values should be sent to this touchpanel in this method!
		/// </summary>
		partial void SetupUI();

		/// <summary>
		/// Implement this in accompanying classes in order to dispose of objects as needed.
		/// </summary>
		partial void DisposeUI();

		/// <summary>
		/// Implement in accompanying classes in order to send initial values to the touchpanels when the root class Threads are started.
		/// </summary>
		partial void InitializeUI();

		/// <summary>
		/// Attempts to initialize values for the current class.
		/// </summary>
		internal void InitializeValues()
		{
			InitializeUI();
		}

		/// <summary>
		/// Calls the partial void DisposeUI in order to allow disposing of custom objects.
		/// </summary>
		public void Dispose()
		{
			DisposeUI();
			foreach (var i in Items)
			{
				i.Dispose();
			}
		}

		/// <summary>
		/// Sets the value of the <see cref="String1"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetString1(string value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(5, (ushort)(425), value, panel);
			var changeEvent = String1Changed;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new StringValueChangedEventArgs(value));
			}
		}
	}
}
