// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Application Version: 0.1.3.101
//		Runtime Version: v4.0.30319
//
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
//		Create a new file with a new partial declaration of the contents of this file and edit that instead.
//		You can use the 'SetupUI()`, 'InitializeUI()', and 'DisposeUI()' partial methods to hook into the construction, initialization, and disposal logic.
// </auto-generated>

using Crestron.SimplSharpPro.DeviceSupport;
using Elegant.EPS.Common;
using System;
using System.Collections.Generic;

namespace EPS.Demo.UI.DemoUI.Components.MainComponents.SubpageRefListsComponents
{
	/// <summary>
	/// Auto-generated SelectedItemLabel class.
	/// </summary>
	public partial class SelectedItemLabel : IDisposable
	{
		/// <summary>
		/// The <see cref="Panel"/> that this object belongs to.
		/// </summary>
		public Panel ParentPanel;

		/// <summary>
		/// Backing field for the <see cref="Text"/> property.
		/// </summary>
		private string text;

		/// <summary>
		/// Backing field for the <see cref="IsVisible"/> property.
		/// </summary>
		private bool isVisible;

		/// <summary>
		/// Raised when the Text value changes.
		/// </summary>
		public event EventHandler<StringValueChangedEventArgs> TextChanged;

		/// <summary>
		/// Raised when the IsVisible value changes.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> IsVisibleChanged;

		/// <summary>
		/// Gets or sets a value indicating what the <see cref="Text"/> join was last set to.
		/// </summary>
		public string Text
		{
			get 
			{
				return text;
			}
			set
			{
				text = value;
				ParentPanel.SendValue((ushort)(2), value);
				var ce = TextChanged;
				if (ce != null)
				{
					ce.Invoke(this, new StringValueChangedEventArgs(value));
					}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating whether the <see cref="IsVisible"/> join was last set to true or false.
		/// </summary>
		public bool IsVisible
		{
			get 
			{
				return isVisible;
			}
			set
			{
				isVisible = value;
				ParentPanel.SendValue((ushort)(3), value);
				var ce = IsVisibleChanged;
				if (ce != null)
				{
					ce.Invoke(this, new BooleanValueChangedEventArgs(value));
					}
			}
		}

		/// <summary>
		/// Creates a new instance of the class.
		/// </summary>
		/// <param name="parent">The class that is the base parent of this one.</param>
		public SelectedItemLabel(Panel parent)
		{
			ParentPanel = parent;

			SetupUI();
		}

		/// <summary>
		/// Implement this in accompanying classes in order to setup functionality on the construction of the root class.
		/// No values should be sent to this touchpanel in this method!
		/// </summary>
		partial void SetupUI();

		/// <summary>
		/// Implement this in accompanying classes in order to dispose of objects as needed.
		/// </summary>
		partial void DisposeUI();

		/// <summary>
		/// Implement in accompanying classes in order to send initial values to the touchpanels when the root class Threads are started.
		/// </summary>
		partial void InitializeUI();

		/// <summary>
		/// Attempts to initialize values for the current class.
		/// </summary>
		internal void InitializeValues()
		{
			InitializeUI();
		}

		/// <summary>
		/// Calls the partial void DisposeUI in order to allow disposing of custom objects.
		/// </summary>
		public void Dispose()
		{
			DisposeUI();
		}

		/// <summary>
		/// Sets the value of the <see cref="Text"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetText(string value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendValue((ushort)(2), value, panel);
			var ce = TextChanged;
			if (ce != null)
			{
				ce.Invoke(this, new StringValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Sets the value of the <see cref="IsVisible"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetIsVisible(bool value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendValue((ushort)(3), value, panel);
			var ce = IsVisibleChanged;
			if (ce != null)
			{
				ce.Invoke(this, new BooleanValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Pulses the IsVisible digital signal. Any local signal changed events won't be fired by this method.
		/// </summary>
		/// <param name="duration">The duration in milliseconds to pulse the signal for.</param>
		public void PulseIsVisible(int duration)
		{
			ParentPanel.Pulse((uint)(3), duration);
		}
	}
}
