// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Application Version: 0.1.4.201
//		Runtime Version: v4.0.30319
//
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
//		Create a new file with a new partial declaration of the contents of this file and edit that instead.
//		You can use the 'SetupUI()`, 'InitializeUI()', and 'DisposeUI()' partial methods to hook into the construction, initialization, and disposal logic.
// </auto-generated>

using Crestron.SimplSharpPro.DeviceSupport;
using Evands.EPS.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace EPS.Demo.UI.DemoUI.Components.MainComponents.SubpageRefListsComponents
{
	/// <summary>
	/// Auto-generated VerticalIconReferenceItemButton class.
	/// </summary>
	public partial class VerticalIconReferenceItemButton : IDisposable, System.ComponentModel.INotifyPropertyChanged
	{
		/// <summary>
		/// The <see cref="Panel"/> that this object belongs to.
		/// </summary>
		public Panel ParentPanel;

		/// <summary>
		/// The offset amount this item uses for its digital joins.
		/// </summary>
		private ushort digitalOffset = 0;

		/// <summary>
		/// The offset amount this item uses for its analog joins.
		/// </summary>
		private ushort analogOffset = 0;

		/// <summary>
		/// The offset amount this item uses for its serial joins.
		/// </summary>
		private ushort serialOffset = 0;

		/// <summary>
		/// The offset amount this item has.
		/// </summary>
		private ushort itemOffset = 0;

		/// <summary>
		/// isActive field.
		/// </summary>
		public bool isActive;

		/// <summary>
		/// pressState field.
		/// </summary>
		public bool pressState;

		/// <summary>
		/// text field.
		/// </summary>
		public string text;

		/// <summary>
		/// Raised when the IsActive value changes.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> IsActiveChanged;

		/// <summary>
		/// Raised when the button is pressed.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> Pressed;

		/// <summary>
		/// Raised when the associated touchpanel event is received.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> PressStateChanged;

		/// <summary>
		/// Raised when the associated touchpanel event is received.
		/// </summary>
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		/// <summary>
		/// Raised when the button is released.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> Released;

		/// <summary>
		/// Raised when the Text value changes.
		/// </summary>
		public event EventHandler<StringValueChangedEventArgs> TextChanged;

		/// <summary>
		/// Gets or sets a value indicating whether the <see cref="IsActive"/> join was last set to true or false.
		/// </summary>
		public bool IsActive
		{
			get 
			{
				return isActive;
			}

			set
			{
				var isChanged = isActive != value;
				isActive = value;
				ParentPanel.SendSmartValue(2, (ushort)(1 + this.digitalOffset), value);
				var changeEvent = IsActiveChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("IsActive"));
					}
				}
			}
		}

		/// <summary>
		/// Gets a value indicating whether the PressState is pressed or released.
		/// </summary>
		public bool PressState
		{
			get 
			{
				return pressState;
			}

			private set
			{
				var isChanged = pressState != value;
				pressState = value;
				var changeEvent = PressStateChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("PressState"));
					}
				}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating what the <see cref="Text"/> join was last set to.
		/// </summary>
		public string Text
		{
			get 
			{
				return text;
			}

			set
			{
				var isChanged = text != value;
				text = value;
				ParentPanel.SendSmartValue(2, (ushort)(1 + this.serialOffset), value);
				var changeEvent = TextChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new StringValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("Text"));
					}
				}
			}
		}

		/// <summary>
		/// Creates a new instance of the class.
		/// </summary>
		/// <param name="parent">The class that is the base parent of this one.</param>
		/// <param name="digitalOffset">The offset amount this item uses for its digital joins.</param>
		/// <param name="analogOffset">The offset amount this item uses for its analog joins.</param>
		/// <param name="serialOffset">The offset amount this item uses for its serial joins.</param>
		/// <param name="itemOffset">The offset amount this item has.</param>
		public VerticalIconReferenceItemButton(Panel parent, ushort digitalOffset, ushort analogOffset, ushort serialOffset, ushort itemOffset)
		{
			ParentPanel = parent;

			this.digitalOffset = digitalOffset;
			this.analogOffset = analogOffset;
			this.serialOffset = serialOffset;
			this.itemOffset = itemOffset;

			if (this.digitalOffset == 0 && this.analogOffset == 0 && this.serialOffset == 0)
			{
				this.digitalOffset = itemOffset;
				this.analogOffset = itemOffset;
				this.serialOffset = itemOffset;
			}

			ParentPanel.Actions.AddBool((uint)(this.digitalOffset + 1), 2, (value) => RaisePressed(value), true);
			ParentPanel.Actions.AddBool((uint)(this.digitalOffset + 1), 2, (value) => RaiseReleased(value), false);

			SetupUI();
		}

		/// <summary>
		/// Implement this in accompanying classes in order to setup functionality on the construction of the root class.
		/// No values should be sent to this touchpanel in this method!
		/// </summary>
		partial void SetupUI();

		/// <summary>
		/// Implement this in accompanying classes in order to dispose of objects as needed.
		/// </summary>
		partial void DisposeUI();

		/// <summary>
		/// Implement in accompanying classes in order to send initial values to the touchpanels when the root class Threads are started.
		/// </summary>
		partial void InitializeUI();

		/// <summary>
		/// Attempts to initialize values for the current class.
		/// </summary>
		internal void InitializeValues()
		{
			InitializeUI();
		}

		/// <summary>
		/// Calls the partial void DisposeUI in order to allow disposing of custom objects.
		/// </summary>
		public void Dispose()
		{
			DisposeUI();
		}

		/// <summary>
		/// Sets the value of the <see cref="IsActive"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetIsActive(bool value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(2, (ushort)(1 + this.digitalOffset), value, panel);
			var changeEvent = IsActiveChanged;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Pulses the IsActive digital signal. Any local signal changed events won't be fired by this method.
		/// </summary>
		/// <param name="duration">The duration in milliseconds to pulse the signal for.</param>
		public void PulseIsActive(int duration)
		{
			ParentPanel.Pulse(2, (uint)(1 + this.digitalOffset), duration);
		}

		/// <summary>
		/// Raises the Pressed event.
		/// </summary>
		/// <param name="value">The pressed event boolean.</param>
		private void RaisePressed(bool value)
		{
			this.PressState = true;
			var changeEvent = this.Pressed;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new BooleanValueChangedEventArgs(true));
			}
		}

		/// <summary>
		/// Raises the Released event.
		/// </summary>
		/// <param name="value">The released event boolean.</param>
		private void RaiseReleased(bool value)
		{
			this.PressState = false;
			var changeEvent = this.Released;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new BooleanValueChangedEventArgs(false));
			}
		}

		/// <summary>
		/// Sets the value of the <see cref="Text"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetText(string value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(2, (ushort)(1 + this.serialOffset), value, panel);
			var changeEvent = TextChanged;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new StringValueChangedEventArgs(value));
			}
		}
	}
}
