// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Application Version: 0.1.3.101
//		Runtime Version: v4.0.30319
//
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
//		Create a new file with a new partial declaration of the contents of this file and edit that instead.
//		You can use the 'SetupUI()`, 'InitializeUI()', and 'DisposeUI()' partial methods to hook into the construction, initialization, and disposal logic.
// </auto-generated>

using Crestron.SimplSharpPro.DeviceSupport;
using EPS.Crestron.Demo.UI.DemoUI.Core;
using System;
using System.Collections.Generic;

namespace EPS.Crestron.Demo.UI.DemoUI.Components.MainComponents.SubpageRefListsComponents
{
	/// <summary>
	/// Auto-generated VerticalIconReference class.
	/// </summary>
	public partial class VerticalIconReference : IDisposable, Elegant.UI.Common.IListItemProvider<VerticalIconReferenceItem>
	{
		/// <summary>
		/// The <see cref="Panel"/> that this object belongs to.
		/// </summary>
		public Panel ParentPanel;

		/// <summary>
		/// Backing field for the <see cref="ItemSelection"/> property.
		/// </summary>
		private ushort itemSelection;

		/// <summary>
		/// Raised when the ItemSelection value changes.
		/// </summary>
		public event EventHandler<UShortValueChangedEventArgs> ItemSelectionChanged;

		/// <summary>
		/// Gets an enumeration of <see cref="VerticalIconReferenceItem"/> items the list contains.
		/// </summary>
		IEnumerable<VerticalIconReferenceItem> Elegant.UI.Common.IListItemProvider<VerticalIconReferenceItem>.Items
		{
			get 
			{
				return this.Items;
			}
		}

		/// <summary>
		/// Gets the array of <see cref="VerticalIconReferenceItem"/> items in the list.
		/// </summary>
		public VerticalIconReferenceItem[] Items { get; private set; }


		/// <summary>
		/// Gets or sets a value indicating what the <see cref="ItemSelection"/> join was last set to.
		/// </summary>
		public ushort ItemSelection
		{
			get 
			{
				return itemSelection;
			}
		}

		/// <summary>
		/// Creates a new instance of the class.
		/// </summary>
		/// <param name="parent">The class that is the base parent of this one.</param>
		public VerticalIconReference(Panel parent)
		{
			ParentPanel = parent;

			Items = new VerticalIconReferenceItem[112]
			{
				new VerticalIconReferenceItem(ParentPanel, 4010, 10, 10, 0),
				new VerticalIconReferenceItem(ParentPanel, 4011, 11, 11, 1),
				new VerticalIconReferenceItem(ParentPanel, 4012, 12, 12, 2),
				new VerticalIconReferenceItem(ParentPanel, 4013, 13, 13, 3),
				new VerticalIconReferenceItem(ParentPanel, 4014, 14, 14, 4),
				new VerticalIconReferenceItem(ParentPanel, 4015, 15, 15, 5),
				new VerticalIconReferenceItem(ParentPanel, 4016, 16, 16, 6),
				new VerticalIconReferenceItem(ParentPanel, 4017, 17, 17, 7),
				new VerticalIconReferenceItem(ParentPanel, 4018, 18, 18, 8),
				new VerticalIconReferenceItem(ParentPanel, 4019, 19, 19, 9),
				new VerticalIconReferenceItem(ParentPanel, 4020, 20, 20, 10),
				new VerticalIconReferenceItem(ParentPanel, 4021, 21, 21, 11),
				new VerticalIconReferenceItem(ParentPanel, 4022, 22, 22, 12),
				new VerticalIconReferenceItem(ParentPanel, 4023, 23, 23, 13),
				new VerticalIconReferenceItem(ParentPanel, 4024, 24, 24, 14),
				new VerticalIconReferenceItem(ParentPanel, 4025, 25, 25, 15),
				new VerticalIconReferenceItem(ParentPanel, 4026, 26, 26, 16),
				new VerticalIconReferenceItem(ParentPanel, 4027, 27, 27, 17),
				new VerticalIconReferenceItem(ParentPanel, 4028, 28, 28, 18),
				new VerticalIconReferenceItem(ParentPanel, 4029, 29, 29, 19),
				new VerticalIconReferenceItem(ParentPanel, 4030, 30, 30, 20),
				new VerticalIconReferenceItem(ParentPanel, 4031, 31, 31, 21),
				new VerticalIconReferenceItem(ParentPanel, 4032, 32, 32, 22),
				new VerticalIconReferenceItem(ParentPanel, 4033, 33, 33, 23),
				new VerticalIconReferenceItem(ParentPanel, 4034, 34, 34, 24),
				new VerticalIconReferenceItem(ParentPanel, 4035, 35, 35, 25),
				new VerticalIconReferenceItem(ParentPanel, 4036, 36, 36, 26),
				new VerticalIconReferenceItem(ParentPanel, 4037, 37, 37, 27),
				new VerticalIconReferenceItem(ParentPanel, 4038, 38, 38, 28),
				new VerticalIconReferenceItem(ParentPanel, 4039, 39, 39, 29),
				new VerticalIconReferenceItem(ParentPanel, 4040, 40, 40, 30),
				new VerticalIconReferenceItem(ParentPanel, 4041, 41, 41, 31),
				new VerticalIconReferenceItem(ParentPanel, 4042, 42, 42, 32),
				new VerticalIconReferenceItem(ParentPanel, 4043, 43, 43, 33),
				new VerticalIconReferenceItem(ParentPanel, 4044, 44, 44, 34),
				new VerticalIconReferenceItem(ParentPanel, 4045, 45, 45, 35),
				new VerticalIconReferenceItem(ParentPanel, 4046, 46, 46, 36),
				new VerticalIconReferenceItem(ParentPanel, 4047, 47, 47, 37),
				new VerticalIconReferenceItem(ParentPanel, 4048, 48, 48, 38),
				new VerticalIconReferenceItem(ParentPanel, 4049, 49, 49, 39),
				new VerticalIconReferenceItem(ParentPanel, 4050, 50, 50, 40),
				new VerticalIconReferenceItem(ParentPanel, 4051, 51, 51, 41),
				new VerticalIconReferenceItem(ParentPanel, 4052, 52, 52, 42),
				new VerticalIconReferenceItem(ParentPanel, 4053, 53, 53, 43),
				new VerticalIconReferenceItem(ParentPanel, 4054, 54, 54, 44),
				new VerticalIconReferenceItem(ParentPanel, 4055, 55, 55, 45),
				new VerticalIconReferenceItem(ParentPanel, 4056, 56, 56, 46),
				new VerticalIconReferenceItem(ParentPanel, 4057, 57, 57, 47),
				new VerticalIconReferenceItem(ParentPanel, 4058, 58, 58, 48),
				new VerticalIconReferenceItem(ParentPanel, 4059, 59, 59, 49),
				new VerticalIconReferenceItem(ParentPanel, 4060, 60, 60, 50),
				new VerticalIconReferenceItem(ParentPanel, 4061, 61, 61, 51),
				new VerticalIconReferenceItem(ParentPanel, 4062, 62, 62, 52),
				new VerticalIconReferenceItem(ParentPanel, 4063, 63, 63, 53),
				new VerticalIconReferenceItem(ParentPanel, 4064, 64, 64, 54),
				new VerticalIconReferenceItem(ParentPanel, 4065, 65, 65, 55),
				new VerticalIconReferenceItem(ParentPanel, 4066, 66, 66, 56),
				new VerticalIconReferenceItem(ParentPanel, 4067, 67, 67, 57),
				new VerticalIconReferenceItem(ParentPanel, 4068, 68, 68, 58),
				new VerticalIconReferenceItem(ParentPanel, 4069, 69, 69, 59),
				new VerticalIconReferenceItem(ParentPanel, 4070, 70, 70, 60),
				new VerticalIconReferenceItem(ParentPanel, 4071, 71, 71, 61),
				new VerticalIconReferenceItem(ParentPanel, 4072, 72, 72, 62),
				new VerticalIconReferenceItem(ParentPanel, 4073, 73, 73, 63),
				new VerticalIconReferenceItem(ParentPanel, 4074, 74, 74, 64),
				new VerticalIconReferenceItem(ParentPanel, 4075, 75, 75, 65),
				new VerticalIconReferenceItem(ParentPanel, 4076, 76, 76, 66),
				new VerticalIconReferenceItem(ParentPanel, 4077, 77, 77, 67),
				new VerticalIconReferenceItem(ParentPanel, 4078, 78, 78, 68),
				new VerticalIconReferenceItem(ParentPanel, 4079, 79, 79, 69),
				new VerticalIconReferenceItem(ParentPanel, 4080, 80, 80, 70),
				new VerticalIconReferenceItem(ParentPanel, 4081, 81, 81, 71),
				new VerticalIconReferenceItem(ParentPanel, 4082, 82, 82, 72),
				new VerticalIconReferenceItem(ParentPanel, 4083, 83, 83, 73),
				new VerticalIconReferenceItem(ParentPanel, 4084, 84, 84, 74),
				new VerticalIconReferenceItem(ParentPanel, 4085, 85, 85, 75),
				new VerticalIconReferenceItem(ParentPanel, 4086, 86, 86, 76),
				new VerticalIconReferenceItem(ParentPanel, 4087, 87, 87, 77),
				new VerticalIconReferenceItem(ParentPanel, 4088, 88, 88, 78),
				new VerticalIconReferenceItem(ParentPanel, 4089, 89, 89, 79),
				new VerticalIconReferenceItem(ParentPanel, 4090, 90, 90, 80),
				new VerticalIconReferenceItem(ParentPanel, 4091, 91, 91, 81),
				new VerticalIconReferenceItem(ParentPanel, 4092, 92, 92, 82),
				new VerticalIconReferenceItem(ParentPanel, 4093, 93, 93, 83),
				new VerticalIconReferenceItem(ParentPanel, 4094, 94, 94, 84),
				new VerticalIconReferenceItem(ParentPanel, 4095, 95, 95, 85),
				new VerticalIconReferenceItem(ParentPanel, 4096, 96, 96, 86),
				new VerticalIconReferenceItem(ParentPanel, 4097, 97, 97, 87),
				new VerticalIconReferenceItem(ParentPanel, 4098, 98, 98, 88),
				new VerticalIconReferenceItem(ParentPanel, 4099, 99, 99, 89),
				new VerticalIconReferenceItem(ParentPanel, 4100, 100, 100, 90),
				new VerticalIconReferenceItem(ParentPanel, 4101, 101, 101, 91),
				new VerticalIconReferenceItem(ParentPanel, 4102, 102, 102, 92),
				new VerticalIconReferenceItem(ParentPanel, 4103, 103, 103, 93),
				new VerticalIconReferenceItem(ParentPanel, 4104, 104, 104, 94),
				new VerticalIconReferenceItem(ParentPanel, 4105, 105, 105, 95),
				new VerticalIconReferenceItem(ParentPanel, 4106, 106, 106, 96),
				new VerticalIconReferenceItem(ParentPanel, 4107, 107, 107, 97),
				new VerticalIconReferenceItem(ParentPanel, 4108, 108, 108, 98),
				new VerticalIconReferenceItem(ParentPanel, 4109, 109, 109, 99),
				new VerticalIconReferenceItem(ParentPanel, 4110, 110, 110, 100),
				new VerticalIconReferenceItem(ParentPanel, 4111, 111, 111, 101),
				new VerticalIconReferenceItem(ParentPanel, 4112, 112, 112, 102),
				new VerticalIconReferenceItem(ParentPanel, 4113, 113, 113, 103),
				new VerticalIconReferenceItem(ParentPanel, 4114, 114, 114, 104),
				new VerticalIconReferenceItem(ParentPanel, 4115, 115, 115, 105),
				new VerticalIconReferenceItem(ParentPanel, 4116, 116, 116, 106),
				new VerticalIconReferenceItem(ParentPanel, 4117, 117, 117, 107),
				new VerticalIconReferenceItem(ParentPanel, 4118, 118, 118, 108),
				new VerticalIconReferenceItem(ParentPanel, 4119, 119, 119, 109),
				new VerticalIconReferenceItem(ParentPanel, 4120, 120, 120, 110),
				new VerticalIconReferenceItem(ParentPanel, 4121, 121, 121, 111)
			};

			ParentPanel.Actions.AddUShort(1, 2, (value) => RaiseItemSelectionChanged(value));

			SetupUI();
		}

		/// <summary>
		/// Implement this in accompanying classes in order to setup functionality on the construction of the root class.
		/// No values should be sent to this touchpanel in this method!
		/// </summary>
		partial void SetupUI();

		/// <summary>
		/// Implement this in accompanying classes in order to dispose of objects as needed.
		/// </summary>
		partial void DisposeUI();

		/// <summary>
		/// Implement in accompanying classes in order to send initial values to the touchpanels when the root class Threads are started.
		/// </summary>
		partial void InitializeUI();

		/// <summary>
		/// Attempts to initialize values for the current class.
		/// </summary>
		internal void InitializeValues()
		{
			InitializeUI();
		}

		/// <summary>
		/// Calls the partial void DisposeUI in order to allow disposing of custom objects.
		/// </summary>
		public void Dispose()
		{
			DisposeUI();
			foreach (var i in Items)
			{
				i.Dispose();
			}
		}

		/// <summary>
		/// Raises the ItemSelectionChanged event.
		/// </summary>
		/// <param name="value">The new value of the property.</param>
		private void RaiseItemSelectionChanged(ushort value)
		{
			itemSelection = value;
			if (ItemSelectionChanged != null)
			{
				ItemSelectionChanged(this, new UShortValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Sends the value to a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void ScrollToItem(bool value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(2, (ushort)(2), value, panel);
		}
	}
}
