// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Application Version: 0.1.3.101
//		Runtime Version: v4.0.30319
//
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
//		Create a new file with a new partial declaration of the contents of this file and edit that instead.
//		You can use the 'SetupUI()`, 'InitializeUI()', and 'DisposeUI()' partial methods to hook into the construction, initialization, and disposal logic.
// </auto-generated>

using Crestron.SimplSharpPro.DeviceSupport;
using EPS.Crestron.Demo.UI.DemoUI.Core;
using System;
using System.Collections.Generic;

namespace EPS.Crestron.Demo.UI.DemoUI.Components.MainComponents.SubpageRefListsComponents
{
	/// <summary>
	/// Auto-generated VerticalIconReferenceItemButton class.
	/// </summary>
	public partial class VerticalIconReferenceItemButton : IDisposable
	{
		/// <summary>
		/// The <see cref="Panel"/> that this object belongs to.
		/// </summary>
		public Panel ParentPanel;

		/// <summary>
		/// The offset amount this item uses for its digital joins.
		/// </summary>
		private ushort digitalOffset = 0;

		/// <summary>
		/// The offset amount this item uses for its analog joins.
		/// </summary>
		private ushort analogOffset = 0;

		/// <summary>
		/// The offset amount this item uses for its serial joins.
		/// </summary>
		private ushort serialOffset = 0;

		/// <summary>
		/// The offset amount this item has.
		/// </summary>
		private ushort itemOffset = 0;

		/// <summary>
		/// Raised when the button is pressed.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> Pressed;

		/// <summary>
		/// Raised when the button is released.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> Released;

		/// <summary>
		/// Creates a new instance of the class.
		/// </summary>
		/// <param name="parent">The class that is the base parent of this one.</param>
		/// <param name="digitalOffset">The offset amount this item uses for its digital joins.</param>
		/// <param name="analogOffset">The offset amount this item uses for its analog joins.</param>
		/// <param name="serialOffset">The offset amount this item uses for its serial joins.</param>
		/// <param name="itemOffset">The offset amount this item has.</param>
		public VerticalIconReferenceItemButton(Panel parent, ushort digitalOffset, ushort analogOffset, ushort serialOffset, ushort itemOffset)
		{
			ParentPanel = parent;

			this.digitalOffset = digitalOffset;
			this.analogOffset = analogOffset;
			this.serialOffset = serialOffset;
			this.itemOffset = itemOffset;

			if (this.digitalOffset == 0 && this.analogOffset == 0 && this.serialOffset == 0)
			{
				this.digitalOffset = itemOffset;
				this.analogOffset = itemOffset;
				this.serialOffset = itemOffset;
			}

			ParentPanel.Actions.AddBool((uint)(this.digitalOffset + 1), 2, (value) => RaisePressed(value), true);
			ParentPanel.Actions.AddBool((uint)(this.digitalOffset + 1), 2, (value) => RaiseReleased(value), false);

			SetupUI();
		}

		/// <summary>
		/// Implement this in accompanying classes in order to setup functionality on the construction of the root class.
		/// No values should be sent to this touchpanel in this method!
		/// </summary>
		partial void SetupUI();

		/// <summary>
		/// Implement this in accompanying classes in order to dispose of objects as needed.
		/// </summary>
		partial void DisposeUI();

		/// <summary>
		/// Implement in accompanying classes in order to send initial values to the touchpanels when the root class Threads are started.
		/// </summary>
		partial void InitializeUI();

		/// <summary>
		/// Attempts to initialize values for the current class.
		/// </summary>
		internal void InitializeValues()
		{
			InitializeUI();
		}

		/// <summary>
		/// Calls the partial void DisposeUI in order to allow disposing of custom objects.
		/// </summary>
		public void Dispose()
		{
			DisposeUI();
		}

		/// <summary>
		/// Raises the Pressed event.
		/// </summary>
		/// <param name="value">The pressed event boolean.</param>
		private void RaisePressed(bool value)
		{
			var ce = Pressed;
			if (ce != null)
			{
				ce.Invoke(this, new BooleanValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Raises the Released event.
		/// </summary>
		/// <param name="value">The released event boolean.</param>
		private void RaiseReleased(bool value)
		{
			var ce = Released;
			if (ce != null)
			{
				ce.Invoke(this, new BooleanValueChangedEventArgs(value));
			}
		}
	}
}
