// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Application Version: 0.1.4.202
//		Runtime Version: v4.0.30319
//
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
//		Create a new file with a new partial declaration of the contents of this file and edit that instead.
//		You can use the 'SetupUI()`, 'InitializeUI()', and 'DisposeUI()' partial methods to hook into the construction, initialization, and disposal logic.
// </auto-generated>

using Crestron.SimplSharpPro.DeviceSupport;
using Evands.EPS.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace EPS.Demo.UI.DemoUI.Components.MainComponents.SubpageRefListsComponents
{
	/// <summary>
	/// Auto-generated VerticalIconReferenceItemDynamicIcon class.
	/// </summary>
	public partial class VerticalIconReferenceItemDynamicIcon : IDisposable, System.ComponentModel.INotifyPropertyChanged
	{
		/// <summary>
		/// The <see cref="Panel"/> that this object belongs to.
		/// </summary>
		public Panel ParentPanel;

		/// <summary>
		/// The offset amount this item uses for its digital joins.
		/// </summary>
		private ushort digitalOffset = 0;

		/// <summary>
		/// The offset amount this item uses for its analog joins.
		/// </summary>
		private ushort analogOffset = 0;

		/// <summary>
		/// The offset amount this item uses for its serial joins.
		/// </summary>
		private ushort serialOffset = 0;

		/// <summary>
		/// The offset amount this item has.
		/// </summary>
		private ushort itemOffset = 0;

		/// <summary>
		/// Backing field for the IconNumber property.
		/// </summary>
		private ushort iconNumber;

		/// <summary>
		/// Raised when the IconNumber value changes.
		/// </summary>
		public event EventHandler<UShortValueChangedEventArgs> IconNumberChanged;

		/// <summary>
		/// Raised when the associated touchpanel event is received.
		/// </summary>
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		/// <summary>
		/// Gets or sets a value indicating what the <see cref="IconNumber"/> join was last set to.
		/// </summary>
		public ushort IconNumber
		{
			get 
			{
				return iconNumber;
			}

			set
			{
				var isChanged = iconNumber != value;
				iconNumber = value;
				ParentPanel.SendSmartValue(2, (ushort)(1 + this.analogOffset), value);
				var changeEvent = IconNumberChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new UShortValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("IconNumber"));
					}
				}
			}
		}

		/// <summary>
		/// Creates a new instance of the class.
		/// </summary>
		/// <param name="parent">The class that is the base parent of this one.</param>
		/// <param name="digitalOffset">The offset amount this item uses for its digital joins.</param>
		/// <param name="analogOffset">The offset amount this item uses for its analog joins.</param>
		/// <param name="serialOffset">The offset amount this item uses for its serial joins.</param>
		/// <param name="itemOffset">The offset amount this item has.</param>
		public VerticalIconReferenceItemDynamicIcon(Panel parent, ushort digitalOffset, ushort analogOffset, ushort serialOffset, ushort itemOffset)
		{
			ParentPanel = parent;

			this.digitalOffset = digitalOffset;
			this.analogOffset = analogOffset;
			this.serialOffset = serialOffset;
			this.itemOffset = itemOffset;

			if (this.digitalOffset == 0 && this.analogOffset == 0 && this.serialOffset == 0)
			{
				this.digitalOffset = itemOffset;
				this.analogOffset = itemOffset;
				this.serialOffset = itemOffset;
			}

			SetupUI();
		}

		/// <summary>
		/// Implement this in accompanying classes in order to setup functionality on the construction of the root class.
		/// No values should be sent to this touchpanel in this method!
		/// </summary>
		partial void SetupUI();

		/// <summary>
		/// Implement this in accompanying classes in order to dispose of objects as needed.
		/// </summary>
		partial void DisposeUI();

		/// <summary>
		/// Implement in accompanying classes in order to send initial values to the touchpanels when the root class Threads are started.
		/// </summary>
		partial void InitializeUI();

		/// <summary>
		/// Attempts to initialize values for the current class.
		/// </summary>
		internal void InitializeValues()
		{
			InitializeUI();
		}

		/// <summary>
		/// Calls the partial void DisposeUI in order to allow disposing of custom objects.
		/// </summary>
		public void Dispose()
		{
			DisposeUI();
		}

		/// <summary>
		/// Sets the value of the <see cref="IconNumber"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetIconNumber(ushort value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendSmartValue(2, (ushort)(1 + this.analogOffset), value, panel);
			var changeEvent = IconNumberChanged;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new UShortValueChangedEventArgs(value));
			}
		}
	}
}
