// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
// </auto-generated>
#region copyright
// <copyright file="DeviceHelper.g.cs" company="Christopher McNeely">
// The MIT License (MIT)
// Copyright (c) Christopher McNeely
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
// NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using Crestron.SimplSharpProInternal;

namespace Evands.EPS.Common
{
    /// <summary>
    /// Device helper methods.
    /// </summary>
    public static class DeviceHelper
    {
        /// <summary>
        /// Attempts device registration, passing feedback to the console and error log if it fails.
        /// </summary>
        /// <param name="dev">The device to register.</param>
        /// <param name="deviceDescriptor">A description of the device for use if it fails and an error is printed.</param>
        /// <returns>Returns true if the registration succeeds, false if it fails for any reason.</returns>
        public static bool Register(this GenericBase dev, string deviceDescriptor)
        {
            if (dev == null)
            {
                CrestronConsole.PrintLine("Couldn't register {0}, the device was null.", deviceDescriptor);
                ErrorLog.Error("Coudln't register {0}, the device was null.", deviceDescriptor);
                return false;
            }
            if (dev.Register() != eDeviceRegistrationUnRegistrationResponse.Success)
            {
                CrestronConsole.PrintLine("Couldn't register {0} for the reason: {1}", deviceDescriptor, dev.RegistrationFailureReason);
                ErrorLog.Error("Coudln't reigster {0} for the reason: {1}.", deviceDescriptor, dev.RegistrationFailureReason);
                return false;
            }

            return true;
        }

        /// <summary>
        /// Attempts device registration, passing feedback to the console and error log if it fails.
        /// </summary>
        /// <param name="dev">The device to register.</param>
        /// <param name="deviceDescriptor">A description of the device for use if it fails and an error is printed.</param>
        /// <returns>Returns true if the registration succeeds, false if it fails for any reason.</returns>
        public static bool Register(this PortDevice dev, string deviceDescriptor)
        {
            if (dev == null)
            {
                CrestronConsole.PrintLine("Couldn't register {0}, the device was null.", deviceDescriptor);
                ErrorLog.Error("Coudln't reigster {0}, the device was null.", deviceDescriptor);
                return false;
            }
            if (dev.Register() != eDeviceRegistrationUnRegistrationResponse.Success)
            {
                CrestronConsole.PrintLine("Couldn't register {0} for the reason: {1}", deviceDescriptor, dev.DeviceRegistrationFailureString);
                ErrorLog.Error("Coudln't reigster {0} for the reason: {1}.", deviceDescriptor, dev.DeviceRegistrationFailureString);
                return false;
            }

            return true;
        }

        /// <summary>
        /// Attempts device unregistration, passing feedback to the console and error log if it fails.
        /// </summary>
        /// <param name="dev">The device to unregister.</param>
        /// <param name="deviceDescriptor">A description of the device for use if it fails and an error is printed.</param>
        /// <returns>Returns true if the unregistration succeeds, false if it fails for any reason.</returns>
        public static bool UnRegister(this GenericBase dev, string deviceDescriptor)
        {
            if (dev == null)
            {
                CrestronConsole.PrintLine("Couldn't unregister {0}, the device was null.", deviceDescriptor);
                ErrorLog.Error("Coudln't unreigster {0}, the device was null.", deviceDescriptor);
                return false;
            }
            if (dev.UnRegister() != eDeviceRegistrationUnRegistrationResponse.Success)
            {
                CrestronConsole.PrintLine("Couldn't unregister {0} for the reason: {1}", deviceDescriptor, dev.RegistrationFailureReason);
                ErrorLog.Error("Couldn't unregister {0} for the reason: {1}", deviceDescriptor, dev.RegistrationFailureReason);
                return false;
            }

            return true;
        }
    }
}