#region copyright
// <copyright file="ListItemBase.g.cs" company="Christopher McNeely">
// The MIT License (MIT)
// Copyright (c) Christopher McNeely
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
// NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
// </auto-generated>
#endregion

using System;

namespace Evands.EPS.Lists
{
    /// <summary>
    /// Provides standardized interactions with items in lists.
    /// </summary>
    /// <typeparam name="T">The type that the item will map values from.</typeparam>
    public abstract class ListItemBase<T>
    {
        /// <summary>
        /// Backing field for the <see cref="IsSelected"/> property.
        /// </summary>
        private bool isSelected = false;

        /// <summary>
        /// Backing field for the <see cref="Value"/> property.
        /// </summary>
        private T value;

        /// <summary>
        /// Used internally by the <see cref="ListBase"/> object to detect selection changes.
        /// </summary>
        internal event Action<ListItemBase<T>, bool> SelectionIsChanging;

        /// <summary>
        /// Raised when the <see cref="IsSelected"/> property has changed.
        /// </summary>
        public event EventHandler<ItemSelectionChangedEventArgs> IsSelectedChanged;

        /// <summary>
        /// Raised when the <see cref="Value"/> property has changed.
        /// </summary>
        public event EventHandler<ValueChangedEventArgs<T>> ValueChanged;

        /// <summary>
        /// Gets or sets whether this item is selected.
        /// </summary>
        public bool IsSelected
        {
            get
            {
                return this.isSelected;
            }

            set
            {
                if (isSelected != value)
                {
                    isSelected = value;
                    var isic = SelectionIsChanging;
                    if (isic != null)
                    {
                        isic.Invoke(this, value);
                    }

                    var isc = IsSelectedChanged;
                    if (isc != null)
                    {
                        isc.Invoke(this, new ItemSelectionChangedEventArgs(value));
                    }
                }
            }
        }

        /// <summary>
        /// Gets or sets the value of the object, as <typeparam name="T"/>.
        /// </summary>
        public T Value
        {
            get { return value; }

            set
            {
                var old = this.value;
                this.value = value;
                ValueIsChanging(value, old);
                var vc = ValueChanged;
                if (vc != null)
                {
                    vc.Invoke(this, new ValueChangedEventArgs<T>(value, old));
                }
            }
        }

        /// <summary>
        /// When overridden by inheriting classes this is raised when the value is changing, immediately prior to the <see cref="ValueChanged"/> event.
        /// </summary>
        /// <param name="newValue">The new value.</param>
        /// <param name="oldValue">The old value.</param>
        protected abstract void ValueIsChanging(T newValue, T oldValue);
    }
}