#region copyright
// <copyright file="ListBase.g.cs" company="Christopher McNeely">
// The MIT License (MIT)
// Copyright (c) Christopher McNeely
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
// NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
// </auto-generated>
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp.Reflection;

namespace Elegant.EPS.Lists
{
    /// <summary>
    /// Provides basic list functionality, simplifying the implementation of lists in code.
    /// </summary>
    /// <typeparam name="T1">The type that the item's values will be.</typeparam>
    /// <typeparam name="T2">The discreet type that the items themselves are.</typeparam>
    public abstract class ListBase<T1, T2> where T2 : ListItemBase<T1>
    {
        /// <summary>
        /// Private method for retrieving the underlying list items.
        /// </summary>
        private Func<T2[]> getItems;

        /// <summary>
        /// Backing field for the <see cref="ValueSource"/> property.
        /// </summary>
        private IEnumerable<T1> valueSource;

        /// <summary>
        /// The list of items.
        /// </summary>
        private Elegant.EPS.Common.IListItemProvider<T2> itemsSource;

        /// <summary>
        /// Backing field for the <see cref="SelectedItem"/> property.
        /// </summary>
        private T2 selectedItem;

        /// <summary>
        /// Raised when the <see cref="SelectedItem"/> property changes.
        /// </summary>
        public event EventHandler<SelectedItemChangedEventArgs<T1>> SelectedItemChanged;

        /// <summary>
        /// Raised when the <see cref="SelectedValue"/> property changes.
        /// </summary>
        public event EventHandler<ValueChangedEventArgs<T1>> SelectedValueChanged;

        /// <summary>
        /// Raised when the <see cref="ValueSource"/> property changes.
        /// </summary>
        public event EventHandler<ValueSourceChanged<T1>> ValueSourceChanged;

        /// <summary>
        /// Gets or sets the list of values that provide values for each item.
        /// </summary>
        public IEnumerable<T1> ValueSource
        {
            get
            {
                return valueSource;
            }

            set
            {
                if (this.getItems == null)
                {
                    throw new ApplicationException(string.Format("Unable to set ValueSource on a list if it hasn't been initialized. Call the Configure method prior to using the ListBase<{0}, {1}>.", typeof(T1).GetCType().Name, typeof(T2).GetCType().Name));
                }

                var oldValueSelection = this.SelectedValue;
                var old = valueSource;
                valueSource = value;

                if (value != null)
                {
                    var values = value.ToArray();
                    var items = this.getItems();
                    for (var i = 0; i < items.Length; i++)
                    {
                        if (i < values.Length)
                        {
                            items[i].Value = values[i];
                        }
                        else
                        {
                            items[i].Value = default(T1);
                        }
                    }
                }

                var vsc = ValueSourceChanged;
                if (vsc != null)
                {
                    vsc.Invoke(this, new ValueSourceChanged<T1>(value, old));
                }
            }
        }

        /// <summary>
        /// Gets the currently selected item from the list.
        /// </summary>
        public T2 SelectedItem
        {
            get
            {
                return selectedItem;
            }

            set
            {
                var old = selectedItem;
                selectedItem = value;

                UpdateItemSelections(value);

                var sic = SelectedItemChanged;
                if (sic != null)
                {
                    sic.Invoke(this, new SelectedItemChangedEventArgs<T1>(value, old));
                }

                var svc = SelectedValueChanged;
                if (svc != null)
                {
                    svc.Invoke(this, new ValueChangedEventArgs<T1>(value != null ? value.Value : default(T1), old != null ? old.Value : default(T1)));
                }
            }
        }

        /// <summary>
        /// Gets the currently selected value from the list of items.
        /// </summary>
        public T1 SelectedValue
        {
            get
            {
                if (selectedItem != null)
                {
                    return selectedItem.Value;
                }

                return default(T1);
            }

            set
            {
                if (value != null)
                {
                    this.SelectedItem = this.getItems().Where(i => i.Value.Equals(value)).FirstOrDefault();
                }
                else
                {
                    this.SelectedItem = null;
                }
            }
        }

        /// <summary>
        /// Configures the list's internal functionality.
        /// <para>This MUST be called prior to using the list.</para>
        /// </summary>
        protected void Configure()
        {
            itemsSource = this as Elegant.EPS.Common.IListItemProvider<T2>;

            if (itemsSource == null)
            {
                throw new ApplicationException("Unable to cast a list to the IListItemProvider type required for ListBase<T1, T2> functionality.");
            }

            this.getItems = () =>
            {
                if (itemsSource.Items != null)
                {
                    return itemsSource.Items.ToArray();
                }
                else
                {
                    return new T2[0];
                }
            };

            foreach (var i in this.getItems())
            {
                i.SelectionIsChanging -= HandleItemSelectionChanges;
                i.SelectionIsChanging += HandleItemSelectionChanges;
            }
        }

        /// <summary>
        /// Processes item selection changes.
        /// </summary>
        /// <param name="sender">The item who's selection status has changed.</param>
        /// <param name="isSelected">A value indicating whether or not the item is selected.</param>
        private void HandleItemSelectionChanges(ListItemBase<T1> sender, bool isSelected)
        {
            if (isSelected)
            {
                SelectedItem = sender as T2;
            }
            else
            {
                if (SelectedItem == sender)
                {
                    SelectedItem = null;
                }
            }
        }

        /// <summary>
        /// Updates the underlying item selections, removing any that are no longer selected.
        /// </summary>
        /// <param name="item">The item that is selected.</param>
        private void UpdateItemSelections(T2 item)
        {
            var items = this.getItems();
            for (var i = 0; i < items.Length; i++)
            {
                if (items[i] != item)
                {
                    items[i].IsSelected = false;
                }
            }
        }
    }
}