// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
// </auto-generated>
#region copyright
// <copyright file="ObjectEventArgs.g.cs" company="Christopher McNeely">
// The MIT License (MIT)
// Copyright (c) Christopher McNeely
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
// NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;

namespace Evands.EPS.Common
{
    /// <summary>
    /// Generic object event args.
    /// </summary>
    public class ObjectEventArgs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectEventArgs"/> class.
        /// </summary>
        /// <param name="args">The smart signal event args.</param>
        public ObjectEventArgs(SmartObjectEventArgs args)
        {
            UserObject = args.Sig.UserObject;
            switch (args.Event)
            {
                case eSigEvent.BoolChange:
                    BoolValue = args.Sig.BoolValue ? true : false;
                    break;
                case eSigEvent.UShortChange:
                    UShortValue = args.Sig.UShortValue;
                    break;
                case eSigEvent.StringChange:
                    StringValue = args.Sig.StringValue;
                    break;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectEventArgs"/> class.
        /// </summary>
        /// <param name="args">The signal event args.</param>
        public ObjectEventArgs(SigEventArgs args)
        {
            UserObject = args.Sig.UserObject;
            switch (args.Event)
            {
                case eSigEvent.BoolChange:
                    BoolValue = args.Sig.BoolValue ? true : false;
                    break;
                case eSigEvent.UShortChange:
                    UShortValue = args.Sig.UShortValue;
                    break;
                case eSigEvent.StringChange:
                    StringValue = args.Sig.StringValue;
                    break;
            }
        }

        /// <summary>
        /// Gets the user object.
        /// </summary>
        public object UserObject { get; private set; }

        /// <summary>
        /// Gets the boolean value.
        /// </summary>
        public bool BoolValue { get; private set; }

        /// <summary>
        /// Gets the ushort value.
        /// </summary>
        public ushort UShortValue { get; private set; }

        /// <summary>
        /// Gets the string value.
        /// </summary>
        public string StringValue { get; private set; }
    }
}
