#region copyright
// <copyright file="SelectedItemChangedEventArgs.g.cs" company="Christopher McNeely">
// The MIT License (MIT)
// Copyright (c) Christopher McNeely
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
// NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
// </auto-generated>
#endregion

using System;

namespace Evands.EPS.Lists
{
    /// <summary>
    /// Provides information regarding selected item changes.
    /// </summary>
    /// <typeparam name="T">The type that the event args describe.</typeparam>
    public class SelectedItemChangedEventArgs<T> : EventArgs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SelectedItemChangedEventArgs"/> class.
        /// </summary>
        /// <param name="newValue">The new value.</param>
        /// <param name="oldValue">The old value.</param>
        public SelectedItemChangedEventArgs(ListItemBase<T> newValue, ListItemBase<T> oldValue)
        {
            NewValue = newValue;
            OldValue = oldValue;
        }

        /// <summary>
        /// Gets the newly selected value.
        /// </summary>
        public ListItemBase<T> NewValue { get; private set; }

        /// <summary>
        /// Gets the previously selected value.
        /// </summary>
        public ListItemBase<T> OldValue { get; private set; }
    }
}