<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<RootNamespace>EPS</RootNamespace>
		<TargetFramework>net10.0-windows</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<AssemblyTitle>Elegant Panel Scaffolding</AssemblyTitle>
		<Product>Elegant Panel Scaffolding</Product>
		<Copyright>Copyright © Christopher McNeely</Copyright>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<OutputPath>bin\$(Configuration)\</OutputPath>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<StartupObject>EPS.App</StartupObject>
		<ApplicationIcon>EPS_Icon.ico</ApplicationIcon>
		<SignAssembly>false</SignAssembly>
		<DelaySign>false</DelaySign>
		<Authors>Christopher McNeely</Authors>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<Version>0.2.0.1000</Version>
	</PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Resources\BooleanValueChangedEventArgs.g.cs" />
    <Compile Remove="Resources\DeviceHelper.g.cs" />
    <Compile Remove="Resources\IListItemProvider.g.cs" />
    <Compile Remove="Resources\ItemSelectionChangedEventArgs.g.cs" />
    <Compile Remove="Resources\ListBase.g.cs" />
    <Compile Remove="Resources\ListItemBase.g.cs" />
    <Compile Remove="Resources\ObjectEventArgs.g.cs" />
    <Compile Remove="Resources\PanelActions.g.cs" />
    <Compile Remove="Resources\PanelUIBase.g.cs" />
    <Compile Remove="Resources\SelectedItemChangedEventArgs.g.cs" />
    <Compile Remove="Resources\StringValueChangedEventArgs.g.cs" />
    <Compile Remove="Resources\UShortValueChangedEventArgs.g.cs" />
    <Compile Remove="Resources\ValueChangedEventArgs.g.cs" />
    <Compile Remove="Resources\ValueSourceChangedEventArgs.g.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Help\Help.css" />
    <None Remove="Help\syntax.css" />
    <None Remove="Help\Help.md" />
    <None Remove="Licenses\Elegant Panel Scaffolding.License.txt" />
    <None Remove="Licenses\Markdig.License.txt" />
    <None Remove="Licenses\Newtsonft Json.NET.License.txt" />
    <None Remove="Licenses\AvalonEdit.License.txt" />
    <None Remove="Licenses\ColorCode-Universal.License.txt" />
    <None Remove="Licenses\SharpZipLib.License.txt" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\DeviceHelper.g.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.40.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="9.0.100" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\BooleanValueChangedEventArgs.g.cs" />
    <Resource Include="Resources\IListItemProvider.g.cs" />
    <Resource Include="Resources\ItemSelectionChangedEventArgs.g.cs" />
    <Resource Include="Resources\ListBase.g.cs" />
    <Resource Include="Resources\ListItemBase.g.cs" />
    <Resource Include="Resources\ObjectEventArgs.g.cs" />
    <Resource Include="Resources\PanelUIBase.g.cs" />
    <Resource Include="Resources\PanelActions.g.cs" />
    <Resource Include="Resources\SelectedItemChangedEventArgs.g.cs" />
    <Resource Include="Resources\StringValueChangedEventArgs.g.cs" />
    <Resource Include="Resources\UShortValueChangedEventArgs.g.cs" />
    <Resource Include="Resources\ValueChangedEventArgs.g.cs" />
    <Resource Include="Resources\ValueSourceChangedEventArgs.g.cs" />
    <EmbeddedResource Include="Help\Help.md" />
    <EmbeddedResource Include="Licenses\Elegant Panel Scaffolding.License.txt" />
    <EmbeddedResource Include="Licenses\Markdig.License.txt" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Blazor\wwwroot\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>