// <auto-generated>
//		This code was generated with Elegant Panel Scaffolding.
//		Application Version: 0.1.4.201
//		Runtime Version: v4.0.30319
//
//		Changes to this file may break expected behavior and will be lost if the code is regenerated.
//		Create a new file with a new partial declaration of the contents of this file and edit that instead.
//		You can use the 'SetupUI()`, 'InitializeUI()', and 'DisposeUI()' partial methods to hook into the construction, initialization, and disposal logic.
// </auto-generated>

using Crestron.SimplSharpPro.DeviceSupport;
using Evands.EPS.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace EPS.Demo.UI.DemoUI.Components.MainComponents.TextControlsComponents
{
	/// <summary>
	/// Auto-generated TextEntry class.
	/// </summary>
	public partial class TextEntry : IDisposable, System.ComponentModel.INotifyPropertyChanged
	{
		/// <summary>
		/// The <see cref="Panel"/> that this object belongs to.
		/// </summary>
		public Panel ParentPanel;

		/// <summary>
		/// enterPressState field.
		/// </summary>
		public bool enterPressState;

		/// <summary>
		/// escapePressState field.
		/// </summary>
		public bool escapePressState;

		/// <summary>
		/// textOverride field.
		/// </summary>
		public string textOverride;

		/// <summary>
		/// text field.
		/// </summary>
		public string text;

		/// <summary>
		/// mode field.
		/// </summary>
		public ushort mode;

		/// <summary>
		/// isFocused field.
		/// </summary>
		public bool isFocused;

		/// <summary>
		/// isEnabled field.
		/// </summary>
		public bool isEnabled;

		/// <summary>
		/// isVisible field.
		/// </summary>
		public bool isVisible;

		/// <summary>
		/// Raised when the button is pressed.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> EnterPressed;

		/// <summary>
		/// Raised when the associated touchpanel event is received.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> EnterPressStateChanged;

		/// <summary>
		/// Raised when the button is released.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> EnterReleased;

		/// <summary>
		/// Raised when the button is pressed.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> EscapePressed;

		/// <summary>
		/// Raised when the associated touchpanel event is received.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> EscapePressStateChanged;

		/// <summary>
		/// Raised when the button is released.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> EscapeReleased;

		/// <summary>
		/// Raised when the IsEnabled value changes.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> IsEnabledChanged;

		/// <summary>
		/// Raised when the IsFocused value changes.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> IsFocusedChanged;

		/// <summary>
		/// Raised when the IsVisible value changes.
		/// </summary>
		public event EventHandler<BooleanValueChangedEventArgs> IsVisibleChanged;

		/// <summary>
		/// Raised when the Mode value changes.
		/// </summary>
		public event EventHandler<UShortValueChangedEventArgs> ModeChanged;

		/// <summary>
		/// Raised when the associated touchpanel event is received.
		/// </summary>
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		/// <summary>
		/// Raised when the Text value changes.
		/// </summary>
		public event EventHandler<StringValueChangedEventArgs> TextChanged;

		/// <summary>
		/// Raised when the TextOverride value changes.
		/// </summary>
		public event EventHandler<StringValueChangedEventArgs> TextOverrideChanged;

		/// <summary>
		/// Gets a value indicating whether the EnterPressState is pressed or released.
		/// </summary>
		public bool EnterPressState
		{
			get 
			{
				return enterPressState;
			}

			private set
			{
				var isChanged = enterPressState != value;
				enterPressState = value;
				var changeEvent = EnterPressStateChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("EnterPressState"));
					}
				}
			}
		}

		/// <summary>
		/// Gets a value indicating whether the EscapePressState is pressed or released.
		/// </summary>
		public bool EscapePressState
		{
			get 
			{
				return escapePressState;
			}

			private set
			{
				var isChanged = escapePressState != value;
				escapePressState = value;
				var changeEvent = EscapePressStateChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("EscapePressState"));
					}
				}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating what the <see cref="TextOverride"/> join was last set to.
		/// </summary>
		public string TextOverride
		{
			get 
			{
				return textOverride;
			}

			set
			{
				var isChanged = textOverride != value;
				textOverride = value;
				ParentPanel.SendValue((ushort)(3), value);
				var changeEvent = TextOverrideChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new StringValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("TextOverride"));
					}
				}
			}
		}

		/// <summary>
		/// Gets a value indicating what the <see cref="Text"/> join was last set to.
		/// </summary>
		public string Text
		{
			get 
			{
				return text;
			}

			private set
			{
				var isChanged = text != value;
				text = value;
				var changeEvent = TextChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new StringValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("Text"));
					}
				}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating what the <see cref="Mode"/> join was last set to.
		/// </summary>
		public ushort Mode
		{
			get 
			{
				return mode;
			}

			set
			{
				var isChanged = mode != value;
				mode = value;
				ParentPanel.SendValue((ushort)(3), value);
				var changeEvent = ModeChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new UShortValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("Mode"));
					}
				}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating whether the <see cref="IsFocused"/> join was last set to true or false.
		/// </summary>
		public bool IsFocused
		{
			get 
			{
				return isFocused;
			}

			set
			{
				var isChanged = isFocused != value;
				isFocused = value;
				ParentPanel.SendValue((ushort)(11), value);
				var changeEvent = IsFocusedChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("IsFocused"));
					}
				}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating whether the <see cref="IsEnabled"/> join was last set to true or false.
		/// </summary>
		public bool IsEnabled
		{
			get 
			{
				return isEnabled;
			}

			set
			{
				var isChanged = isEnabled != value;
				isEnabled = value;
				ParentPanel.SendValue((ushort)(12), value);
				var changeEvent = IsEnabledChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("IsEnabled"));
					}
				}
			}
		}

		/// <summary>
		/// Gets or sets a value indicating whether the <see cref="IsVisible"/> join was last set to true or false.
		/// </summary>
		public bool IsVisible
		{
			get 
			{
				return isVisible;
			}

			set
			{
				var isChanged = isVisible != value;
				isVisible = value;
				ParentPanel.SendValue((ushort)(13), value);
				var changeEvent = IsVisibleChanged;
				if(changeEvent != null)
				{
					changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
				}

				if(isChanged)
				{
					var propertyChangeEvent = PropertyChanged;
					if (propertyChangeEvent != null)
					{
						propertyChangeEvent.Invoke(this, new PropertyChangedEventArgs("IsVisible"));
					}
				}
			}
		}

		/// <summary>
		/// Creates a new instance of the class.
		/// </summary>
		/// <param name="parent">The class that is the base parent of this one.</param>
		public TextEntry(Panel parent)
		{
			ParentPanel = parent;

			ParentPanel.Actions.AddBool(7, (value) => RaiseEnterPressed(value), true);
			ParentPanel.Actions.AddBool(7, (value) => RaiseEnterReleased(value), false);
			ParentPanel.Actions.AddBool(8, (value) => RaiseEscapePressed(value), true);
			ParentPanel.Actions.AddBool(8, (value) => RaiseEscapeReleased(value), false);
			ParentPanel.Actions.AddString(4, (value) => RaiseTextChanged(value));
			ParentPanel.Actions.AddBool(11, (value) => RaiseIsFocusedChanged(value));

			SetupUI();
		}

		/// <summary>
		/// Implement this in accompanying classes in order to setup functionality on the construction of the root class.
		/// No values should be sent to this touchpanel in this method!
		/// </summary>
		partial void SetupUI();

		/// <summary>
		/// Implement this in accompanying classes in order to dispose of objects as needed.
		/// </summary>
		partial void DisposeUI();

		/// <summary>
		/// Implement in accompanying classes in order to send initial values to the touchpanels when the root class Threads are started.
		/// </summary>
		partial void InitializeUI();

		/// <summary>
		/// Attempts to initialize values for the current class.
		/// </summary>
		internal void InitializeValues()
		{
			InitializeUI();
		}

		/// <summary>
		/// Calls the partial void DisposeUI in order to allow disposing of custom objects.
		/// </summary>
		public void Dispose()
		{
			DisposeUI();
		}

		/// <summary>
		/// Raises the EnterPressed event.
		/// </summary>
		/// <param name="value">The pressed event boolean.</param>
		private void RaiseEnterPressed(bool value)
		{
			this.EnterPressState = true;
			var changeEvent = this.EnterPressed;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new BooleanValueChangedEventArgs(true));
			}
		}

		/// <summary>
		/// Raises the EnterReleased event.
		/// </summary>
		/// <param name="value">The released event boolean.</param>
		private void RaiseEnterReleased(bool value)
		{
			this.EnterPressState = false;
			var changeEvent = this.EnterReleased;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new BooleanValueChangedEventArgs(false));
			}
		}

		/// <summary>
		/// Raises the EscapePressed event.
		/// </summary>
		/// <param name="value">The pressed event boolean.</param>
		private void RaiseEscapePressed(bool value)
		{
			this.EscapePressState = true;
			var changeEvent = this.EscapePressed;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new BooleanValueChangedEventArgs(true));
			}
		}

		/// <summary>
		/// Raises the EscapeReleased event.
		/// </summary>
		/// <param name="value">The released event boolean.</param>
		private void RaiseEscapeReleased(bool value)
		{
			this.EscapePressState = false;
			var changeEvent = this.EscapeReleased;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new BooleanValueChangedEventArgs(false));
			}
		}

		/// <summary>
		/// Sets the value of the <see cref="TextOverride"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetTextOverride(string value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendValue((ushort)(3), value, panel);
			var changeEvent = TextOverrideChanged;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new StringValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Raises the TextChanged event.
		/// </summary>
		/// <param name="value">The new value of the property.</param>
		private void RaiseTextChanged(string value)
		{
			this.Text = value;
		}

		/// <summary>
		/// Sets the value of the <see cref="Mode"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetMode(ushort value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendValue((ushort)(3), value, panel);
			var changeEvent = ModeChanged;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new UShortValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Sends the value to a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void LatchSetFocus(bool value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendValue((ushort)(9), value, panel);
		}

		/// <summary>
		/// Pulses the SetFocus digital signal.
		/// </summary>
		/// <param name="duration">The duration in milliseconds to pulse the signal for.</param>
		public void SetFocus(int duration)
		{
			ParentPanel.Pulse((uint)(9), duration);
		}

		/// <summary>
		/// Sends the value to a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void LatchRemoveFocus(bool value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendValue((ushort)(10), value, panel);
		}

		/// <summary>
		/// Pulses the RemoveFocus digital signal.
		/// </summary>
		/// <param name="duration">The duration in milliseconds to pulse the signal for.</param>
		public void RemoveFocus(int duration)
		{
			ParentPanel.Pulse((uint)(10), duration);
		}

		/// <summary>
		/// Sets the value of the <see cref="IsFocused"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetIsFocused(bool value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendValue((ushort)(11), value, panel);
		}

		/// <summary>
		/// Pulses the IsFocused digital signal. Any local signal changed events won't be fired by this method.
		/// </summary>
		/// <param name="duration">The duration in milliseconds to pulse the signal for.</param>
		public void PulseIsFocused(int duration)
		{
			ParentPanel.Pulse((uint)(11), duration);
		}

		/// <summary>
		/// Raises the IsFocusedChanged event.
		/// </summary>
		/// <param name="value">The new value of the property.</param>
		private void RaiseIsFocusedChanged(bool value)
		{
			this.IsFocused = value;
		}

		/// <summary>
		/// Sets the value of the <see cref="IsEnabled"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetIsEnabled(bool value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendValue((ushort)(12), value, panel);
			var changeEvent = IsEnabledChanged;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Pulses the IsEnabled digital signal. Any local signal changed events won't be fired by this method.
		/// </summary>
		/// <param name="duration">The duration in milliseconds to pulse the signal for.</param>
		public void PulseIsEnabled(int duration)
		{
			ParentPanel.Pulse((uint)(12), duration);
		}

		/// <summary>
		/// Sets the value of the <see cref="IsVisible"/> join on a single touchpanel.
		/// </summary>
		/// <param name="value">The new value for the join on the touchpanel.</param>
		/// <param name="panel">The panel to change the associated join value on.</param>
		public void SetIsVisible(bool value, BasicTriListWithSmartObject panel)
		{
			ParentPanel.SendValue((ushort)(13), value, panel);
			var changeEvent = IsVisibleChanged;
			if (changeEvent != null)
			{
				changeEvent.Invoke(this, new BooleanValueChangedEventArgs(value));
			}
		}

		/// <summary>
		/// Pulses the IsVisible digital signal. Any local signal changed events won't be fired by this method.
		/// </summary>
		/// <param name="duration">The duration in milliseconds to pulse the signal for.</param>
		public void PulseIsVisible(int duration)
		{
			ParentPanel.Pulse((uint)(13), duration);
		}
	}
}
